services:
  postgres:
    image: postgres:16
    container_name: taskmanager_postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
        interval: 5s
        timeout: 5s
        retries: 5
        start_period: 10s

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: taskmanager_pgadmin
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  backend:
    build: backend
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app


volumes:
  postgres_data:
  pgadmin_data:
